apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore-outbox
spec:
  # See: https://docs.dapr.io/reference/components-reference/supported-state-stores/setup-postgresql-v1/
  type: state.postgresql 
  version: v1
  metadata:
    # Connection string
    - name: connectionString
      value: "host=localhost user=postgres password=ucprulz port=5432 connect_timeout=10 database=ucp_state"
    # Name of the table where to store the state (optional)
    - name: tableName
      value: "ucp_state"
    # Name of the table where to store metadata used by Dapr (optional)
    - name: metadataTableName
      value: "ucp_metadata"
    # DO NOT use as actor statestore
    - name: actorStateStore
      value: "false"
    # Name of the pubsub component to use for publishing outbox messages
    - name: outboxPublishPubsub
      value: "pubsub"
    # Name of the topic to publish outbox messages to
    - name: outboxPublishTopic
      value: "outbox"
    # Configures whether to discard outbox messages when the state is missing (optional)
    - name: outboxDiscardWhenMissingState #Optional. Defaults to false
      value: false

    # Timeout for database operations, as a Go duration or number of seconds (optional)
    #- name: timeout
    #  value: 20
    # Cleanup interval in seconds, to remove expired rows (optional)
    #- name: cleanupInterval
    #  value: "1h"
    # Maximum number of connections pooled by this component (optional)
    #- name: maxConns
    #  value: 0
    # Max idle time for connections before they're closed (optional)
    #- name: connectionMaxIdleTime
    #  value: 0
    # Controls the default mode for executing queries. (optional)
    #- name: queryExecMode
    #  value: ""
